name: Exportar apuntes TFG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Crear ZIP
        run: zip -r tfg.zip apuntes bibliografia

      - name: Crear TAR
        run: tar -cvf tfg.tar apuntes bibliografia

      - name: Subir archivos como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: tfg-export
          path: |
            tfg.zip
            tfg.tar
